apiVersion: v1
kind: Secret
metadata:
  name: blinkshare-secrets
  namespace: blinkshare
type: Opaque
stringData:
  postgres-db: blinkshare
  postgres-user: CHANGE_ME_POSTGRES_USER
  postgres-password: CHANGE_ME_POSTGRES_PASSWORD
  connection-string-postgres: Host=postgres;Port=5432;Database=blinkshare;Username=CHANGE_ME_POSTGRES_USER;Password=CHANGE_ME_POSTGRES_PASSWORD
  garage-rpc-secret: CHANGE_ME_64_HEX_GARAGE_RPC_SECRET
  object-storage-access-key: CHANGE_ME_GARAGE_ACCESS_KEY
  object-storage-secret-key: CHANGE_ME_GARAGE_SECRET_KEY
