apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: blinkshare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:17-alpine
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: blinkshare-secrets
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: blinkshare-secrets
                  key: postgres-user
          command:
            - sh
            - -c
            - until pg_isready -h postgres -p 5432 -U "$POSTGRES_USER" -d "$POSTGRES_DB"; do sleep 2; done
        - name: wait-for-object-storage
          image: busybox:1.36
          command:
            - sh
            - -c
            - until nc -z object-storage 9000; do sleep 2; done
      containers:
        - name: worker
          image: docker.io/pi9x/blinkshare-worker:0.1.4
          envFrom:
            - configMapRef:
                name: blinkshare-config
          env:
            - name: ConnectionStrings__Postgres
              valueFrom:
                secretKeyRef:
                  name: blinkshare-secrets
                  key: connection-string-postgres
            - name: ObjectStorage__AccessKey
              valueFrom:
                secretKeyRef:
                  name: blinkshare-secrets
                  key: object-storage-access-key
            - name: ObjectStorage__SecretKey
              valueFrom:
                secretKeyRef:
                  name: blinkshare-secrets
                  key: object-storage-secret-key
